@HostAddress = http://localhost:5126

### Crear un Artista de prueba
POST {{HostAddress}}/api/Artistas
Content-Type: application/json

{
  "nombreCompleto": "Gustavo Cerati",
  "nombreArtistico": "Cerati",
  "anioInicio": 1982,
  "nacionalidad": "Argentina",
  "discografica": "Sony Music"
}